<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Menu;
use Illuminate\Support\Str;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        $menus = [
            [
                'restaurant_id' => 1,
                'item_name' => 'Nasi Goreng',
                'description' => 'Fried rice with special seasoning',
                'price' => 30000,
                'size' => 'large',
                'spice_level' => 'medium',
                'category' => 'main',
                'quantity' => 20,
                'is_active' => true,
                'image_url' => 'https://images.unsplash.com/photo-1645696329525-8ec3bee460a9?q=80&w=1629&auto=format&fit=crop',
            ],
            [
                'restaurant_id' => 1,
                'item_name' => 'Mie Goreng',
                'description' => 'Stir-fried noodles with veggies',
                'price' => 28000,
                'size' => 'large',
                'spice_level' => 'medium',
                'category' => 'main',
                'quantity' => 15,
                'is_active' => true,
                'image_url' => 'https://images.unsplash.com/photo-1680675494363-75bbf9838a09?q=80&w=1170&auto=format&fit=crop',
            ],
            [
                'restaurant_id' => 1,
                'item_name' => 'Nasi Ayam Goreng',
                'description' => 'Fried chicken with rice',
                'price' => 35000,
                'size' => 'large',
                'spice_level' => 'medium',
                'category' => 'main',
                'quantity' => 18,
                'is_active' => true,
                'image_url' => 'https://images.unsplash.com/photo-1732185269471-b62b52ca46f9?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            ],
            [
                'restaurant_id' => 1,
                'item_name' => 'Mie Rebus',
                'description' => 'Noodles in a savory broth',
                'price' => 25000,
                'size' => 'medium',
                'spice_level' => 'low',
                'category' => 'main',
                'quantity' => 22,
                'is_active' => true,
                'image_url' => 'https://www.pamperedchef.ca/iceberg/com/recipe/2214569-2-lg.jpg',
            ],
            [
                'restaurant_id' => 1,
                'item_name' => 'Nasi & Mie Goreng',
                'description' => 'Combination of fried rice & noodles',
                'price' => 38000,
                'size' => 'large',
                'spice_level' => 'medium',
                'category' => 'main',
                'quantity' => 12,
                'is_active' => true,
                'image_url' => 'https://cdn0-production-images-kly.akamaized.net/PVzytSOiRTJWEtf3UyqEobyUH1Y=/0x28:999x591/1200x675/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/4091808/original/034443400_1658107777-shutterstock_2047628240.jpg',
            ],
            [
                'restaurant_id' => 1,
                'item_name' => 'Nasi Goreng Spesial',
                'description' => 'Special fried rice with extra toppings',
                'price' => 40000,
                'size' => 'large',
                'spice_level' => 'high',
                'category' => 'main',
                'quantity' => 10,
                'is_active' => true,
                'image_url' => 'https://takestwoeggs.com/wp-content/uploads/2025/03/Overhead-plate-Nasi-Goreng-Indonesian-Fried-Rice.webp',
            ],
            [
                'restaurant_id' => 1,
                'item_name' => 'Es Teh Manis',
                'description' => 'Sweet iced tea',
                'price' => 12000,
                'size' => 'small',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 30,
                'is_active' => true,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfPWkYhq0H7Xh6RSm2kIPnYbqCbrNbsFlaDw&s',
            ],
            [
                'restaurant_id' => 1,
                'item_name' => 'Air Mineral',
                'description' => 'Bottled mineral water',
                'price' => 8000,
                'size' => 'small',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 50,
                'is_active' => true,
                'image_url' => 'https://parto.id/asset/foto_produk/9UwtN3qZEW0UyvkjTWuWaoSTmfGQrkWZ9fdYW8OP.jpg',
            ],
            [
                'restaurant_id' => 1,
                'item_name' => 'Americano',
                'description' => 'Espresso diluted with hot water',
                'price' => 25000,
                'size' => 'small',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 20,
                'is_active' => true,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdOcl7DjiVojBeSmBhEmkZ9SOik9TTNwLqk7gsWjKcebWcgXBITgwMIT-2iCUtE63wIU4&usqp=CAU',
            ],
            [
                'restaurant_id' => 1,
                'item_name' => 'Chocolate Hazelnuts',
                'description' => 'Chocolate drink with hazelnut',
                'price' => 30000,
                'size' => 'medium',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 15,
                'is_active' => true,
                'image_url' => 'https://cocosutra.com/cdn/shop/files/Cocosutra_Hazelnut_Hot_Chocolate_Drink.png?v=1694304694&width=550',
            ],
            [
                'restaurant_id' => 1,
                'item_name' => 'Lemon Tea',
                'description' => 'Iced lemon tea',
                'price' => 18000,
                'size' => 'small',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 25,
                'is_active' => true,
                'image_url' => 'https://radarmukomuko.bacakoran.co/upload/3f0929ad4f76a951272ebc96154dbd4a.jpg',
            ],
            [
                'restaurant_id' => 1,
                'item_name' => 'Juice Alpukat',
                'description' => 'Avocado juice',
                'price' => 22000,
                'size' => 'medium',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 20,
                'is_active' => true,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLUC4fjuwFhEwJUyqaDifG_6OTUUwwYQ7xaQ&s',
            ],
            [
                'restaurant_id' => 1,
                'item_name' => 'Juice Mangga',
                'description' => 'Mango juice',
                'price' => 20000,
                'size' => 'medium',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 18,
                'is_active' => true,
                'image_url' => 'https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2023/03/02/istockphoto-904617420-170667a-1-2881139756.png',
            ],
            [
                'restaurant_id' => 1,
                'item_name' => 'Thai Tea',
                'description' => 'Sweet Thai milk tea',
                'price' => 25000,
                'size' => 'medium',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 22,
                'is_active' => true,
                'image_url' => 'https://ukhuwah.sch.id/wp-content/uploads/2024/12/tai1.jpeg',
            ],
            [
                'restaurant_id' => 1,
                'item_name' => 'Cappucino',
                'description' => 'Espresso with steamed milk foam',
                'price' => 28000,
                'size' => 'small',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 20,
                'is_active' => true,
                'image_url' => 'https://www.cuisinart.com/dw/image/v2/ABAF_PRD/on/demandware.static/-/Sites-us-cuisinart-sfra-Library/default/dw30047d66/images/recipe-Images/cappuccino1-recipe.jpg?sw=1200&sh=1200&sm=fit',
            ],

            [
                'restaurant_id' => 3,
                'item_name' => 'Nasi Goreng',
                'description' => 'Fried rice with special seasoning',
                'price' => 30000,
                'size' => 'large',
                'spice_level' => 'medium',
                'category' => 'main',
                'quantity' => 20,
                'is_active' => true,
                'image_url' => 'https://images.unsplash.com/photo-1645696329525-8ec3bee460a9?q=80&w=1629&auto=format&fit=crop',
            ],
            [
                'restaurant_id' => 3,
                'item_name' => 'Mie Goreng',
                'description' => 'Stir-fried noodles with veggies',
                'price' => 28000,
                'size' => 'large',
                'spice_level' => 'medium',
                'category' => 'main',
                'quantity' => 15,
                'is_active' => true,
                'image_url' => 'https://images.unsplash.com/photo-1680675494363-75bbf9838a09?q=80&w=1170&auto=format&fit=crop',
            ],
            [
                'restaurant_id' => 3,
                'item_name' => 'Nasi Ayam Goreng',
                'description' => 'Fried chicken with rice',
                'price' => 35000,
                'size' => 'large',
                'spice_level' => 'medium',
                'category' => 'main',
                'quantity' => 18,
                'is_active' => true,
                'image_url' => 'https://images.unsplash.com/photo-1732185269471-b62b52ca46f9?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            ],
            [
                'restaurant_id' => 3,
                'item_name' => 'Mie Rebus',
                'description' => 'Noodles in a savory broth',
                'price' => 25000,
                'size' => 'medium',
                'spice_level' => 'low',
                'category' => 'main',
                'quantity' => 22,
                'is_active' => true,
                'image_url' => 'https://www.pamperedchef.ca/iceberg/com/recipe/2214569-2-lg.jpg',
            ],
            [
                'restaurant_id' => 3,
                'item_name' => 'Nasi & Mie Goreng',
                'description' => 'Combination of fried rice & noodles',
                'price' => 38000,
                'size' => 'large',
                'spice_level' => 'medium',
                'category' => 'main',
                'quantity' => 12,
                'is_active' => true,
                'image_url' => 'https://cdn0-production-images-kly.akamaized.net/PVzytSOiRTJWEtf3UyqEobyUH1Y=/0x28:999x591/1200x675/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/4091808/original/034443400_1658107777-shutterstock_2047628240.jpg',
            ],
            [
                'restaurant_id' => 3,
                'item_name' => 'Nasi Goreng Spesial',
                'description' => 'Special fried rice with extra toppings',
                'price' => 40000,
                'size' => 'large',
                'spice_level' => 'high',
                'category' => 'main',
                'quantity' => 10,
                'is_active' => true,
                'image_url' => 'https://takestwoeggs.com/wp-content/uploads/2025/03/Overhead-plate-Nasi-Goreng-Indonesian-Fried-Rice.webp',
            ],
            [
                'restaurant_id' => 3,
                'item_name' => 'Es Teh Manis',
                'description' => 'Sweet iced tea',
                'price' => 12000,
                'size' => 'small',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 30,
                'is_active' => true,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfPWkYhq0H7Xh6RSm2kIPnYbqCbrNbsFlaDw&s',
            ],
            [
                'restaurant_id' => 3,
                'item_name' => 'Air Mineral',
                'description' => 'Bottled mineral water',
                'price' => 8000,
                'size' => 'small',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 50,
                'is_active' => true,
                'image_url' => 'https://parto.id/asset/foto_produk/9UwtN3qZEW0UyvkjTWuWaoSTmfGQrkWZ9fdYW8OP.jpg',
            ],
            [
                'restaurant_id' => 3,
                'item_name' => 'Americano',
                'description' => 'Espresso diluted with hot water',
                'price' => 25000,
                'size' => 'small',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 20,
                'is_active' => true,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdOcl7DjiVojBeSmBhEmkZ9SOik9TTNwLqk7gsWjKcebWcgXBITgwMIT-2iCUtE63wIU4&usqp=CAU',
            ],
            [
                'restaurant_id' => 3,
                'item_name' => 'Chocolate Hazelnuts',
                'description' => 'Chocolate drink with hazelnut',
                'price' => 30000,
                'size' => 'medium',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 15,
                'is_active' => true,
                'image_url' => 'https://cocosutra.com/cdn/shop/files/Cocosutra_Hazelnut_Hot_Chocolate_Drink.png?v=1694304694&width=550',
            ],
            [
                'restaurant_id' => 3,
                'item_name' => 'Lemon Tea',
                'description' => 'Iced lemon tea',
                'price' => 18000,
                'size' => 'small',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 25,
                'is_active' => true,
                'image_url' => 'https://radarmukomuko.bacakoran.co/upload/3f0929ad4f76a951272ebc96154dbd4a.jpg',
            ],
            [
                'restaurant_id' => 3,
                'item_name' => 'Juice Alpukat',
                'description' => 'Avocado juice',
                'price' => 22000,
                'size' => 'medium',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 20,
                'is_active' => true,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLUC4fjuwFhEwJUyqaDifG_6OTUUwwYQ7xaQ&s',
            ],
            [
                'restaurant_id' => 3,
                'item_name' => 'Juice Mangga',
                'description' => 'Mango juice',
                'price' => 20000,
                'size' => 'medium',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 18,
                'is_active' => true,
                'image_url' => 'https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2023/03/02/istockphoto-904617420-170667a-1-2881139756.png',
            ],
            [
                'restaurant_id' => 3,
                'item_name' => 'Thai Tea',
                'description' => 'Sweet Thai milk tea',
                'price' => 25000,
                'size' => 'medium',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 22,
                'is_active' => true,
                'image_url' => 'https://ukhuwah.sch.id/wp-content/uploads/2024/12/tai1.jpeg',
            ],
            [
                'restaurant_id' => 3,
                'item_name' => 'Cappucino',
                'description' => 'Espresso with steamed milk foam',
                'price' => 28000,
                'size' => 'small',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 20,
                'is_active' => true,
                'image_url' => 'https://www.cuisinart.com/dw/image/v2/ABAF_PRD/on/demandware.static/-/Sites-us-cuisinart-sfra-Library/default/dw30047d66/images/recipe-Images/cappuccino1-recipe.jpg?sw=1200&sh=1200&sm=fit',
            ],


            [
                'restaurant_id' => 2,
                'item_name' => 'Nasi Goreng',
                'description' => 'Fried rice with special seasoning',
                'price' => 30000,
                'size' => 'large',
                'spice_level' => 'medium',
                'category' => 'main',
                'quantity' => 20,
                'is_active' => true,
                'image_url' => 'https://images.unsplash.com/photo-1645696329525-8ec3bee460a9?q=80&w=1629&auto=format&fit=crop',
            ],
            [
                'restaurant_id' => 2,
                'item_name' => 'Mie Goreng',
                'description' => 'Stir-fried noodles with veggies',
                'price' => 28000,
                'size' => 'large',
                'spice_level' => 'medium',
                'category' => 'main',
                'quantity' => 15,
                'is_active' => true,
                'image_url' => 'https://images.unsplash.com/photo-1680675494363-75bbf9838a09?q=80&w=1170&auto=format&fit=crop',
            ],
            [
                'restaurant_id' => 2,
                'item_name' => 'Nasi Ayam Goreng',
                'description' => 'Fried chicken with rice',
                'price' => 35000,
                'size' => 'large',
                'spice_level' => 'medium',
                'category' => 'main',
                'quantity' => 18,
                'is_active' => true,
                'image_url' => 'https://images.unsplash.com/photo-1732185269471-b62b52ca46f9?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            ],
            [
                'restaurant_id' => 2,
                'item_name' => 'Mie Rebus',
                'description' => 'Noodles in a savory broth',
                'price' => 25000,
                'size' => 'medium',
                'spice_level' => 'low',
                'category' => 'main',
                'quantity' => 22,
                'is_active' => true,
                'image_url' => 'https://www.pamperedchef.ca/iceberg/com/recipe/2214569-2-lg.jpg',
            ],
            [
                'restaurant_id' => 2,
                'item_name' => 'Nasi & Mie Goreng',
                'description' => 'Combination of fried rice & noodles',
                'price' => 38000,
                'size' => 'large',
                'spice_level' => 'medium',
                'category' => 'main',
                'quantity' => 12,
                'is_active' => true,
                'image_url' => 'https://cdn0-production-images-kly.akamaized.net/PVzytSOiRTJWEtf3UyqEobyUH1Y=/0x28:999x591/1200x675/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/4091808/original/034443400_1658107777-shutterstock_2047628240.jpg',
            ],
            [
                'restaurant_id' => 2,
                'item_name' => 'Nasi Goreng Spesial',
                'description' => 'Special fried rice with extra toppings',
                'price' => 40000,
                'size' => 'large',
                'spice_level' => 'high',
                'category' => 'main',
                'quantity' => 10,
                'is_active' => true,
                'image_url' => 'https://takestwoeggs.com/wp-content/uploads/2025/03/Overhead-plate-Nasi-Goreng-Indonesian-Fried-Rice.webp',
            ],
            [
                'restaurant_id' => 2,
                'item_name' => 'Es Teh Manis',
                'description' => 'Sweet iced tea',
                'price' => 12000,
                'size' => 'small',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 30,
                'is_active' => true,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfPWkYhq0H7Xh6RSm2kIPnYbqCbrNbsFlaDw&s',
            ],
            [
                'restaurant_id' => 2,
                'item_name' => 'Air Mineral',
                'description' => 'Bottled mineral water',
                'price' => 8000,
                'size' => 'small',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 50,
                'is_active' => true,
                'image_url' => 'https://parto.id/asset/foto_produk/9UwtN3qZEW0UyvkjTWuWaoSTmfGQrkWZ9fdYW8OP.jpg',
            ],
            [
                'restaurant_id' => 2,
                'item_name' => 'Americano',
                'description' => 'Espresso diluted with hot water',
                'price' => 25000,
                'size' => 'small',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 20,
                'is_active' => true,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdOcl7DjiVojBeSmBhEmkZ9SOik9TTNwLqk7gsWjKcebWcgXBITgwMIT-2iCUtE63wIU4&usqp=CAU',
            ],
            [
                'restaurant_id' => 2,
                'item_name' => 'Chocolate Hazelnuts',
                'description' => 'Chocolate drink with hazelnut',
                'price' => 30000,
                'size' => 'medium',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 15,
                'is_active' => true,
                'image_url' => 'https://cocosutra.com/cdn/shop/files/Cocosutra_Hazelnut_Hot_Chocolate_Drink.png?v=1694304694&width=550',
            ],
            [
                'restaurant_id' => 2,
                'item_name' => 'Lemon Tea',
                'description' => 'Iced lemon tea',
                'price' => 18000,
                'size' => 'small',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 25,
                'is_active' => true,
                'image_url' => 'https://radarmukomuko.bacakoran.co/upload/3f0929ad4f76a951272ebc96154dbd4a.jpg',
            ],
            [
                'restaurant_id' => 2,
                'item_name' => 'Juice Alpukat',
                'description' => 'Avocado juice',
                'price' => 22000,
                'size' => 'medium',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 20,
                'is_active' => true,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLUC4fjuwFhEwJUyqaDifG_6OTUUwwYQ7xaQ&s',
            ],
            [
                'restaurant_id' => 2,
                'item_name' => 'Juice Mangga',
                'description' => 'Mango juice',
                'price' => 20000,
                'size' => 'medium',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 18,
                'is_active' => true,
                'image_url' => 'https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2023/03/02/istockphoto-904617420-170667a-1-2881139756.png',
            ],
            [
                'restaurant_id' => 2,
                'item_name' => 'Thai Tea',
                'description' => 'Sweet Thai milk tea',
                'price' => 25000,
                'size' => 'medium',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 22,
                'is_active' => true,
                'image_url' => 'https://ukhuwah.sch.id/wp-content/uploads/2024/12/tai1.jpeg',
            ],
            [
                'restaurant_id' => 2,
                'item_name' => 'Cappucino',
                'description' => 'Espresso with steamed milk foam',
                'price' => 28000,
                'size' => 'small',
                'spice_level' => 'low',
                'category' => 'drink',
                'quantity' => 20,
                'is_active' => true,
                'image_url' => 'https://www.cuisinart.com/dw/image/v2/ABAF_PRD/on/demandware.static/-/Sites-us-cuisinart-sfra-Library/default/dw30047d66/images/recipe-Images/cappuccino1-recipe.jpg?sw=1200&sh=1200&sm=fit',
            ],





        ];

        Menu::insert($menus);
    }
}
